# Site settings
title: Instituto Mutir√£o
description: Uma rede de pessoas programando a democracia digital
analytics_id: UA-XXXXX-X

collections:
- apresentacao
- objetivos
- cases
- clientes
- depoimentos
- oss
- midia
- equipe

# Build settings
markdown: kramdown

gems: [jekyll-sass]
